oc_platform_home:
    path:      /{page}
    defaults:
        _controller: MattPlatformBundle:Advert:index
        page:   1
    requirements:
        page:   \d*
    
oc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: MattPlatformBundle:Advert:view
    requirements:
        id: \d+
    
oc_platform_add:
    path:      /add
    defaults:
        _controller: MattPlatformBundle:Advert:add

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: MattPlatformBundle:Advert:edit
    requirements:
        id:  \d+

oc_platform_delete:
    path:      /delete
    defaults:
        _controller: MattPlatformBundle:Advert:delete
    requirements:
        id:  \d+
        


